DEVICE_PATH := device/realme/RMX3761

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-2a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a75

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-2a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a55

# Assertation
TARGET_OTA_ASSERT_DEVICE := RMX3761

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := RMX3761
TARGET_NO_BOOTLOADER := true
#TARGET_USES_UEFI := true

# Ensure recovery is included in vendor_boot
BOARD_INCLUDE_RECOVERY_RAMDISK := true
BOARD_USES_VENDOR_BOOT := true
BOARD_VENDOR_BOOTIMAGE_FILE_SYSTEM_TYPE := "ramdisk"
BOARD_KERNEL_CMDLINE += androidboot.force_normal_boot=1
BOARD_KERNEL_CMDLINE += androidboot.slot_suffix=$(getprop ro.boot.slot_suffix)

# Define separate vendor_boot.img
TARGET_NO_RECOVERY := true
BOARD_BUILD_VENDOR_BOOT_IMAGE := true
TARGET_COPY_OUT_VENDOR_BOOT := vendor_boot
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
BOARD_VENDOR_BOOTIMAGE_FILE_SYSTEM_TYPE := "ramdisk"

# Path to TWRP recovery binary
TARGET_RECOVERY_DEVICE_MODULES := twrp

# Build Rule
ALLOW_MISSING_DEPENDENCIES := true

# Kernel
TARGET_NO_KERNEL := true
TARGET_KERNEL_ARCH := arm64
BOARD_RAMDISK_USE_LZ4 := true
TARGET_KERNEL_HEADER_ARCH := arm64

# Sepolicy
BOARD_VENDOR_SEPOLICY_DIRS += device/RMX3761/sepolicy/precompiled

# Kernel
BOARD_VENDOR_CMDLINE := console=ttyS1,115200n8 buildvariant=user buildvariant=eng
BOARD_VENDOR_BASE := 0x00000000
BOARD_PAGE_SIZE := 4096
BOARD_RAMDISK_OFFSET := 0x05400000
#BOARD_HEADER_SIZE := 2128
#BOARD_DTB_SIZE := 123569
BOARD_DTB_OFFSET := 0x01f00000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_TAGS_OFFSET := 0x00000100
#BOARD_HEADER_VERSION := 4       
#BOARD_BOOT_HEADER_VERSION := 4
BOARD_VENDOR_BOOT_HEADER_VERSION := 4

# DTBO
BOARD_KERNEL_SEPARATED_DTBO := true

# Partitions
BOARD_FLASH_BLOCK_SIZE := 262144
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 104857600
BOARD_SYSTEMIMAGE_PARTITION_TYPE := erofs
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := erofs
TARGET_COPY_OUT_VENDOR := vendor
BOARD_SUPER_PARTITION_SIZE := 16777216000
BOARD_SUPER_PARTITION_GROUPS := realme_dynamic_partitions
BOARD_REALME_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor product system_ext odm vendor_dlkm
BOARD_REALME_DYNAMIC_PARTITIONS_SIZE := 16777214976

# Platform
TARGET_BOARD_PLATFORM := ums9230

# Recovery
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TARGET_USERIMAGES_USE_EROFS := true
TARGET_USERIMAGES_USE_F2FS := true

# Treble
BOARD_VNDK_VERSION := current

# Verified Boot
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3

# TWRP Configurations
# TW_DEFAULT_LANGUAGE := zh_CN
# TW_EXTRA_LANGUAGES := true
TW_THEME := portrait_hdpi
TW_INCLUDE_FASTBOOTD := true

# Debug
TARGET_USES_LOGD := true
TWRP_INCLUDE_LOGCAT := true
